#!/bin/bash
sudo apt update -y && sudo apt upgrade -y
sudo apt install -y htop net-tools openssh-server sshfs proftpd espeak geany git python python-pip python-smbus python3-dev python3-venv python3-pip python3-smbus apache2 php mysql-server mysql-common mysql-client phpmyadmin mplayer
sudo apt autoclean
sudo apt autoremove
sudo apt dist-upgrade
sudo service apache2 restart
sudo service mysql restart
sudo pip3 install virtualenv
virtualenv /home/$USER/pythonenv
pip install requests
pip3 install mps-youtube youtube-dl
git clone https://github.com/mps-youtube/mps-youtube
sudo cp bin/gad				/usr/bin
sudo cp bin/ziz				/usr/bin
sudo cp bin/gpio/dht11		/usr/bin
sudo cp bin/gpio/lcd		/usr/bin
sudo cp bin/pogoda			/usr/bin
sudo cp bin/gpio/domofon	/usr/bin
sudo cp bin/domobot			/usr/bin
sudo cp bin/autogit			/usr/bin
sudo cp -r www/* /var/www/html/domobot/		#musi być ta gwiazdka, bo inaczej kopiuje do www

