#!/bin/bash
echo "Nazwa Bazy danych?"
read DBNAME
echo "Nazwa Użytkownika Bazy danych?"
read DBUSER
echo "Hasło do Bazy Danych?"
read DBPASS
sudo echo "<?php" | sudo tee /var/www/html/domobot/config/db.php
sudo echo "define('DB_CMS_HOST', 'localhost');" | sudo tee -a /var/www/html/domobot/config/db.php
sudo echo "define('DB_CMS_BAZA', '$DBNAME');" | sudo tee -a /var/www/html/domobot/config/db.php
sudo echo "define('DB_CMS_LOGIN', '$DBUSER');" | sudo tee -a /var/www/html/domobot/config/db.php
sudo echo "define('DB_CMS_HASLO', '$DBPASS');" | sudo tee -a /var/www/html/domobot/config/db.php
sudo echo "?>" | sudo tee -a /var/www/html/domobot/config/db.php