#!/bin/bash
echo "Wifi SSID (nazwa Twojej domowej sieci WiFi)"
read SSID
echo "Hasło WiFi?"
read PASS

if uname | grep -q W64; then
#win64

	PHP=$null
	PYTHON=$null
	C="..\\..\\domobot\\wifi.h"
	SUDO=""

	$SUDO mkdir $HOME/Documents/domobot

else
#unix

	PHP=/var/www/html/domobot/config/wifi.php
	PYTHON=/usr/share/domobot/wifi.py
	C=/usr/share/domobot/wifi.h
	SUDO=sudo

	$SUDO mkdir /usr/share/domobot

fi


echo ""
echo "W formacie PHP: $PHP"
echo ""
echo "<?php" | tee $PHP
echo "define('WIFI_SSID', '$SSID');" | tee $PHP
echo "define('WIFI_PASS', '$PASS');" | tee -a $PHP
echo "?>" | tee -a $PHP

echo ""
echo "W formacie Python: $PYTHON"
echo ""
echo "wifi=dict(" | $SUDO tee $PYTHON
echo "    ssid='$SSID'," | $SUDO tee -a $PYTHON
echo "    pass='$PASS'," | $SUDO tee -a $PYTHON
echo ")" | $SUDO tee -a $PYTHON

echo ""
echo "W formacie C: $C"
echo ""
echo "const char* WIFI_SSID=\"$SSID\";" | $SUDO tee $C
echo "const char* WIFI_PASS=\"$PASS\";" | $SUDO tee -a $C
